siteName: Marginalia
instagramUrl: http://instagram.com/marginalia.label
soundcloudUrl: https://soundcloud.com/marginalialabel
beatportUrl: https://www.beatport.com/label/marginalia/115971
youtubeUrl: https://www.youtube.com/@marginalialabel
tiktokUrl: http://www.tiktok.com/marginalia.label
facebookUrl: https://www.facebook.com/marginalia.label
merchUrl: https://merchmarginalia.myshopify.com/
demoEmail: elif@marginalialabel.com
layloUrl: https://laylo.com/elifmusique/marginaliacommunity
